In [9]:
import jax.numpy as jnp
import numpy as np
import itertools
from rich import print

In [10]:
k_h = 3
k_w = 3
half_k_h = k_h // 2
half_k_w = k_w // 2
i_h = 4
i_w = 4

In [13]:
for x, y in itertools.product(
    range(half_k_h, i_h - half_k_h), range(half_k_w, i_w - half_k_w)
):
    print(x, y)

1 1

1 2

2 1

2 2

In [18]:
a = np.array([[2, 3, 4], [6, 7, 8], [10, 11, 12]])
a

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [17]:
a.mean()

7.0

In [5]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
b = np.pad(a, (1, 1), mode="edge")
b

array([[1, 1, 2, 3, 3],
       [1, 1, 2, 3, 3],
       [4, 4, 5, 6, 6],
       [7, 7, 8, 9, 9],
       [7, 7, 8, 9, 9]])